# Allocate measured payloads into the known code caves for one firmware key.
#
# Input 1: code-cave table
# Input 2: payload_sizes_<version>.tsv
# Output: payload_layout_<version>.tsv on stdout and Make variables in mkfile.

function fail(message)
{
	print "generate_payload_layout: " message > "/dev/stderr"
	exit 1
}

function hex_value(text,    i, digit, value)
{
	if (text !~ /^0[xX][0-9a-fA-F]+$/)
		fail("invalid hexadecimal address: " text)

	value = 0
	for (i = 3; i <= length(text); i++) {
		digit = index("0123456789abcdef", tolower(substr(text, i, 1))) - 1
		value = value * 16 + digit
	}
	return value
}

function align4(value)
{
	return int((value + 3) / 4) * 4
}

BEGIN {
	FS = "[[:space:]]+"
	if (version == "" || mkfile == "")
		fail("version and mkfile are required")

	print "# Generated by patches/generate_payload_layout.awk; do not edit." > mkfile
	print "# payload\taddress\tsize\tend_exclusive"
}

FNR == NR {
	if ($0 ~ /^[[:space:]]*(#|$)/ || $1 != version)
		next

	start = hex_value($2)
	end = hex_value($3)
	if (start % 4 != 0 || end <= start)
		fail("invalid cave for " version ": " $2 ".." $3)
	if (cave_count && start < cave_end[cave_count])
		fail("overlapping or unsorted caves for " version)

	cave_count++
	cave_start[cave_count] = start
	cave_end[cave_count] = end
	cave_next[cave_count] = start
	next
}

$0 ~ /^[[:space:]]*(#|$)/ {
	next
}

{
	if (!cave_count)
		fail("no code caves defined for " version)

	payload = $1
	size = $2 + 0
	if (payload !~ /^[a-zA-Z_][a-zA-Z0-9_]*$/ || size <= 0)
		fail("invalid payload size row: " $0)
	if (seen[payload]++)
		fail("duplicate payload: " payload)

	placed = 0
	for (i = 1; i <= cave_count; i++) {
		address = align4(cave_next[i])
		payload_end = address + size
		if (payload_end <= cave_end[i]) {
			cave_next[i] = payload_end
			placed = 1
			break
		}
	}
	if (!placed)
		fail(payload " (" size " bytes) does not fit in " version " code caves")

	printf "%s\t0x%08X\t%d\t0x%08X\n", payload, address, size, payload_end
	printf "payload_addr_%s_%s := 0x%08X\n", version, payload, address >> mkfile
	printf "payload_size_%s_%s := %d\n", version, payload, size >> mkfile
}

END {
	if (!cave_count)
		fail("no code caves defined for " version)
}
